### PR TITLE
add aggregated view and edit roles for crd

### PR DESCRIPTION
**Pull request by just1900**
This is a continuation of https://github.com/kubediag/kubediag-helm/pull/6

### CODE REVIEW

**Comment by April-Q** [comment]
`kubediag-view` and `kubediag-edit` will be installed by default through helm, so make the same changes here. You can configure this file in rbac/kustomization.yaml.

**Comment by just1900** [comment]
@April-Q PTAL

**Comment by April-Q** [comment]
> @April-Q PTAL

Check of `code verify` have failed,  pls make your code clean.

**Comment by just1900** [comment]
I've added changes to manifests, ci passed 🎉

**Comment by April-Q** [comment]
LGTM

**Pull request merged**
